### PR TITLE
Update/python 3 version

### PR DESCRIPTION
**Pull request by vsoch**
This is a quick bump up to v0.0.19 so that the package can be properly released on pypi. I also changed a few missed iteritems to items.

@rwblair take a look and merge when it's suitable! I will release v0.0.19 on pypi when it's merged, and we can do further iterations for any other work you want to do.

### CODE REVIEW

**Review by rwblair — APPROVED** [review]
Amazing thats all that needed to change!

**Comment by rwblair** [comment]
I don't actually have write access to this repository, can you make me an admin of this organization?

**Comment by vsoch** [comment]
yep! One second...

**Comment by vsoch** [comment]
Sorry got distracted and wanted to make a logo :) You're invited!

We don't actually have any tests here, so it's pretty much a blind fix. I'd say for now it's worth doing a quick fix and release, and then having an issue open to write official tests. As we test with other tools (expfactory, for example) we can get a sense of if python 2 is a deal breaker. Python 2 is... going away... so hopefully not :)

**Comment by vsoch** [comment]
Actually let me see if I can throw together something quick on circle. Merging without testing makes me feel ill lol.

**Comment by vsoch** [comment]
Interesting, it looks like the API is different, or is returning many concepts instead of 1. For example, here I'm asking for "anxiety" but it returns everything related to it:

```
### TESTING CONCEPT QUERIES:
http://cognitiveatlas.org/api/v-alpha/concept?id=trm_5022ef7599294
Result Includes:<pandas:data frame><json:dict><txt:str><url:str>
{'creation_time': 1512660639996, 'concepts': [{'creation_time': 1512660629809, 'relationship': 'KINDOF', 'definition_text': 'a complex of psychological phenomena that involve some degree of arousal and valence (positive/negative)', 'name': 'emotion', 'id_user': 'usr_0000000000', 'def_id_user': 'usr_49a467bf4e0db', 'def_event_stamp': '2012-03-28T17:54:40', 'event_stamp': '2009-06-22T19:12:55', 'id_concept_class': 'ctp_C8', 'def_id': 'def_4f7350605133e', 'alias': '', 'last_updated': 1512660629809, 'id': 'trm_4a3fd79d0a17f'}], 'conceptclasses': [{'creation_time': 1512660843754, 'display_order': 3, 'relationship': 'CLASSIFIEDUNDER', 'name': 'Emotion', 'last_updated': 1512660843754, 'id': 'ctp_C8', 'description': 'Emotion'}], 'relationships': [{'creation_time': 1512660629809, 'relationship': 'KINDOF', 'definition_text': 'a complex of psychological phenomena that involve some degree of arousal and valence (positive/negative)', 'name': 'emotion', 'id_user': 'usr_0000000000', 'def_id_user': 'usr_49a467bf4e0db', 'def_event_stamp': '2012-03-28T17:54:40', 'event_stamp': '2009-06-22T19:12:55', 'direction': 'parent', 'id_concept_class': 'ctp_C8', 'def_id': 'def_4f7350605133e', 'alias': '', 'last_updated': 1512660629809, 'id': 'trm_4a3fd79d0a17f'}], 'type': 'concept', 'definition_text': 'An aversive psychophysiological state characterized by fear, worry, or concern associated with current or impending threat often elicited by general and specific interoceptive or exteroceptive cues.', 'name': 'anxiety', 'def_id_user': 'usr_51ba954cf0abe', 'def_event_stamp': '2013-06-14T04:19:52', 'contrasts': [{'creation_time': 1512660680582, 'event_stamp': '2013-11-29T22:25:03', 'id_user': 'usr_51bc76ae9636c', 'name': 'anxiety', 'last_updated': 1512660680582, 'relationship': 'MEASUREDBY', 'id': 'cnt_5299143fed521'}, {'creation_time': 1512660674110, 'event_stamp': '2013-10-14T20:43:29', 'id_user': 'usr_51bc76ae9636c', 'name': 'anxious', 'last_updated': 1512660674110, 'relationship': 'MEASUREDBY', 'id': 'cnt_525c5771523cb'}, {'creation_time': 1512660672561, 'event_stamp': '2013-10-01T22:22:20', 'id_user': 'usr_51bc76ae9636c', 'name': 'anxiety problems', 'last_updated': 1512660672561, 'relationship': 'MEASUREDBY', 'id': 'cnt_524b4b1c6dd43'}, {'creation_time': 1512660671891, 'event_stamp': '2013-09-23T15:18:22', 'id_user': 'usr_51bc76ae9636c', 'name': 'anxiety', 'last_updated': 1512660671891, 'relationship': 'MEASUREDBY', 'id': 'cnt_52405bbeec6bc'}, {'creation_time': 1512660671004, 'event_stamp': '2013-09-21T19:47:34', 'id_user': 'usr_51bc76ae9636c', 'name': 'Separation Anxiety - Severity Score', 'last_updated': 1512660671004, 'relationship': 'MEASUREDBY', 'id': 'cnt_523df7d6697ef'}, {'creation_time': 1512660670623, 'event_stamp': '2013-09-21T19:44:51', 'id_user': 'usr_51bc76ae9636c', 'name': 'General Anxiety Disorder - Severity Score', 'last_updated': 1512660670623, 'relationship': 'MEASUREDBY', 'id': 'cnt_523df733af85f'}, {'creation_time': 1512660665001, 'event_stamp': '2012-08-09T20:51:20', 'id_user': 'usr_4f177506dde77', 'name': 'no cue Uâ\x80\x93no cue N', 'last_updated': 1512660665001, 'relationship': 'MEASUREDBY', 'id': 'cnt_502422c805b89'}, {'creation_time': 1512660664608, 'event_stamp': '2012-08-08T23:05:52', 'id_user': 'usr_4f177506dde77', 'name': 'meditation versus control theta oscillations', 'last_updated': 1512660664608, 'relationship': 'MEASUREDBY', 'id': 'cnt_5022f0d06e757'}], 'event_stamp': '2012-08-08T23:00:05', 'id_concept_class': 'ctp_C8', 'def_id': 'def_51ba99e738d7c', 'id_user': 'usr_4f177506dde77', 'alias': '', 'citations': [], 'last_updated': 1512660639996, 'id': 'trm_5022ef7599294'}
```
If this is expected behavior (because there are more terms than there were before) I can update the test. If not, let's discuss what has changed!

**Comment by vsoch** [comment]
I think it's just an indexing issue, before there was a list returned, and now it's a single dict. So we go from this:

```
result.json[0]["name"],concept_name
```
to this:

```
result.json["name"],concept_name
```
If cognitiveatlas.org is serving the API and this is the only place, it shouldn't be an issue to update.

**Comment by vsoch** [comment]
Timestamp format is also different, shouldn't be an issue other than for testing:

```
AssertionError: '2010-10-06T21:46:50' != '2010-10-06 21:46:50'
- 2010-10-06T21:46:50
?           ^
+ 2010-10-06 21:46:50
?           ^

```

**Comment by vsoch** [comment]
wooooo go circle go!

**Comment by vsoch** [comment]
okay so what I added is a workflow, one for each of python2 and python3 (and hey, python 4 when it comes out! just kidding :P )

image

I had a few circle config blips, but the tests pass for each of the endpoints (at least the ones I know about that are implemented here).

**Comment by vsoch** [comment]
Tests are good, so I think this is at least a good start, and we can merge if you are good. I'll release on pypi short after.

image

**Comment by vsoch** [comment]
@rwblair merge at your convenience.

**Comment by rwblair** [comment]
Amazing work @vsoch, thank you.

Re the api differences: I never did get the site working 100% the same as the old one, my measure of success was if expfactory-docker and neurovault could still make calls that worked. Glad to see not too much had to change in the tests.

**Comment by vsoch** [comment]
Release on pypi https://pypi.org/project/cognitiveatlas/0.1.9/

**Pull request merged**
